server:
  port: 9125

logquality:
  project_name: testapp
  file: false
  filebeat: false
  logstash:
    connection: true
    host: 192.168.1.15
    port: 31501

management:
  endpoints:
    web:
      exposure:
        include: metrics