server:
  port: 9125

logquality:
  file: true
  filebeat: false
  logstash:
    connection: false
    host: localhost
    port: 5044
  cassandra:
    connection: false
    host: localhost
    port: 9042
    keyspace: logquality
    tableName: test
