server:
  port: 9125

logquality:
  file: true
  filebeat: false
  logstash:
    connection: true
    host: localhost
    port: 5044
  cassandra:
    connection: false
    host: localhost
    port: 9042
    keyspace: logquality
    tableName: test

management:
  endpoints:
    web:
      exposure:
        include: metrics

spring:
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.health.HealthEndpointAutoConfiguration